# Generated by Django 5.0.6 on 2024-05-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_product_price_alter_product_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='compound',
            field=models.TextField(default='Состав', verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='product',
            name='compound_en',
            field=models.TextField(default='Состав', null=True, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='product',
            name='compound_ru',
            field=models.TextField(default='Состав', null=True, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='product',
            name='compound_uz',
            field=models.TextField(default='Состав', null=True, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='Описание', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(default='Описание', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=models.TextField(default='Описание', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_uz',
            field=models.TextField(default='Описание', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/', verbose_name='Фото'),
        ),
    ]
