# Generated by Django 5.0.6 on 2024-05-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_product_compound_alter_product_compound_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_type',
            field=models.CharField(choices=[('dobroe', 'Доброе'), ('alsafi', 'Альсафи')], default='dobroe', max_length=10),
        ),
    ]
