# Generated by Django 5.0.6 on 2024-05-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_certificates'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage/images/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото на слайдере',
                'verbose_name_plural': 'Фотки на слайдере',
            },
        ),
    ]
