# Generated by Django 5.0.6 on 2024-05-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_homeimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Новинка ?'),
        ),
    ]
