# Generated by Django 5.0.6 on 2024-05-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_product_is_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='partners/images/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото партнера',
                'verbose_name_plural': 'Фото партнеров',
            },
        ),
    ]
