# Generated by Django 5.0.6 on 2024-06-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_certificates_image_alter_homeimages_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=30, verbose_name='Года')),
                ('company_name', models.CharField(default='BIO NATURAL FOOD', max_length=40, verbose_name='Название компании')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='Заголовок')),
                ('title_uz', models.CharField(max_length=50, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('description_uz', models.TextField(null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Элемент истории',
                'verbose_name_plural': 'Элементы истории',
            },
        ),
    ]
