# Generated by Django 5.0.6 on 2024-06-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='year_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Года'),
        ),
        migrations.AddField(
            model_name='about',
            name='year_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Года'),
        ),
        migrations.AddField(
            model_name='about',
            name='year_uz',
            field=models.CharField(max_length=30, null=True, verbose_name='Года'),
        ),
    ]
