# Generated by Django 5.0.6 on 2024-06-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_about_year_en_about_year_ru_about_year_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='energy_value',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Энергетическая ценность'),
        ),
        migrations.AddField(
            model_name='product',
            name='food_value',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Пищевая ценность'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Объем'),
        ),
    ]
