# Generated by Django 5.0.6 on 2024-06-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_product_energy_value_product_food_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Срок годности'),
        ),
    ]
