# Generated by Django 5.0.6 on 2024-06-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Срок годности'),
        ),
        migrations.AddField(
            model_name='product',
            name='date_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Срок годности'),
        ),
        migrations.AddField(
            model_name='product',
            name='date_uz',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Срок годности'),
        ),
        migrations.AddField(
            model_name='product',
            name='energy_value_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Энергетическая ценность'),
        ),
        migrations.AddField(
            model_name='product',
            name='energy_value_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Энергетическая ценность'),
        ),
        migrations.AddField(
            model_name='product',
            name='energy_value_uz',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Энергетическая ценность'),
        ),
        migrations.AddField(
            model_name='product',
            name='food_value_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Пищевая ценность'),
        ),
        migrations.AddField(
            model_name='product',
            name='food_value_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Пищевая ценность'),
        ),
        migrations.AddField(
            model_name='product',
            name='food_value_uz',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Пищевая ценность'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Объем'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Объем'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_uz',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Объем'),
        ),
    ]
