# Generated by Django 5.0.6 on 2024-06-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_product_date_en_product_date_ru_product_date_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeimages',
            name='image',
        ),
        migrations.AddField(
            model_name='homeimages',
            name='desktop_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/images/', verbose_name='Фото на десктоп'),
        ),
        migrations.AddField(
            model_name='homeimages',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/images/', verbose_name='Фото на телефоны'),
        ),
    ]
